name: Test and dispatch event to delivery action
env:
  DISPATCH_REPO : "briana-crm/briana-deploy"
  DELIVERY_EVENT: "delivery"
  SERVICE_NAME  : "briana_stack_hello-service"

on:
  push: 
    branches:
      - main

jobs:
  push_event:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch delivery action
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ env.DISPATCH_REPO }}
          event-type: ${{ env.DELIVERY_EVENT }}
          client-payload: |
            '{"repo_name": "${{ github.event.repository.name }}", \
              "commit_hash": "${{ github.sha }}", \
              "service_name": "${{ env.SERVICE_NAME }}"}' \
