# This is a basic workflow to help you get started with Actions

name: CI
env:
  PACKAGE_NAME : "${{ github.repository }}:latest"

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push_to_registry:
      name: Push Docker image to GitHub Packages
      runs-on: ubuntu-latest
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
        - name: Docker meta
          id: docker_meta
          uses: crazy-max/ghaction-docker-meta@v1.11.0
          with:
            images: ${{ secrets.DOCKERHUB_USERNAME }}/briana-client
          
        - name: Push to Docker Registry
          uses: docker/build-push-action@v2.3.0
          with:
            push: true
            tags: ${{ steps.docker_meta.outputs.tags }}

  # This workflow contains a single job called "build"
  push_event:
    needs: [push_to_registry]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: briana-crm/briana-test
          event-type: push_candidate
          client-payload: '{"name": "${{ steps.docker_meta.outputs.tags }}"}'
